{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "912e6a56",
   "metadata": {},
   "source": [
    "# Build123d Introductory Examples\n",
    "\n",
    "The examples are taken from the [official documentation](https://build123d.readthedocs.io/en/latest/introductory_examples.html). Only the Builder mode code is implemented here."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "18699c8f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import build123d as bd\n",
    "from ocp_vscode import show"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "49ac2b21",
   "metadata": {},
   "source": [
    "## 1. Simple Rectangular Plate"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c72eafd2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using port 3939\n",
      "Jupyter kernel running\n",
      "Jupyter connection file path written to /home/vscode/.ocpvscode\n",
      "+"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "length, width, thickness = 80.0, 60.0, 10.0\n",
    "\n",
    "with bd.BuildPart() as ex1:\n",
    "    bd.Box(length, width, thickness)\n",
    "\n",
    "show(ex1)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c5d1a530",
   "metadata": {},
   "source": [
    "## 2. Plate with Hole"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "09377e71",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "length, width, thickness = 80.0, 60.0, 10.0\n",
    "center_hole_dia = 22.0\n",
    "\n",
    "with bd.BuildPart() as ex2:\n",
    "    bd.Box(length, width, thickness)\n",
    "    bd.Cylinder(radius=center_hole_dia / 2, height=thickness,\n",
    "                mode=bd.Mode.SUBTRACT)\n",
    "\n",
    "show(ex2)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0cbe9dfe",
   "metadata": {},
   "source": [
    "## 3. Extruded prismatic solid"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b7d53979",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "length, width, thickness = 80.0, 60.0, 10.0\n",
    "\n",
    "with bd.BuildPart() as ex3:\n",
    "    with bd.BuildSketch() as ex3_sk:\n",
    "        bd.Circle(width)\n",
    "        bd.Rectangle(length / 2, width / 2,\n",
    "                     mode=bd.Mode.SUBTRACT)\n",
    "    bd.extrude(amount=2 * thickness)\n",
    "\n",
    "show(ex3)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "542ca0df",
   "metadata": {},
   "source": [
    "## 4. Building Profiles using lines and arcs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "06f15131",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "length, width, thickness = 80.0, 60.0, 10.0\n",
    "\n",
    "with bd.BuildPart() as ex4:\n",
    "    with bd.BuildSketch() as ext4_sk:\n",
    "        with bd.BuildLine() as ex4_ln:\n",
    "            l1 = bd.Line((0, 0), (length, 0))\n",
    "            l2 = bd.Line((length, 0), (length, width))\n",
    "            l3 = bd.ThreePointArc((length, width), (width, width*1.5), (0, width))\n",
    "            # For tangent arc use the following:\n",
    "            # l3 = ThreePointArc((length, width),\n",
    "            #                    (length/2, width+length/2),\n",
    "            #                    (0, width))\n",
    "            l4 = bd.Line((0, width), (0, 0))\n",
    "        bd.make_face()\n",
    "    bd.extrude(amount=thickness)\n",
    "\n",
    "show(ex4)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a94076ca",
   "metadata": {},
   "source": [
    "## 5. Moving the current working point"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "24051c8f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "a, b, c, d = 90, 45, 15, 7.5\n",
    "\n",
    "with bd.BuildPart() as ex5:\n",
    "    with bd.BuildSketch() as ex5_sk:\n",
    "        bd.Circle(a)\n",
    "        with bd.Locations((b, 0.0)):\n",
    "            bd.Rectangle(c, c, mode=bd.Mode.SUBTRACT)\n",
    "        with bd.Locations((0, b)):\n",
    "            bd.Circle(d, mode=bd.Mode.SUBTRACT)\n",
    "    bd.extrude(amount=c)\n",
    "\n",
    "show(ex5)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e60dfbbc",
   "metadata": {},
   "source": [
    "## 6. Using Points Lists"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "6602a759",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "a, b, c = 80, 60, 10\n",
    "\n",
    "with bd.BuildPart() as ex6:\n",
    "    with bd.BuildSketch() as ex6_sk:\n",
    "        bd.Circle(a)\n",
    "        with bd.Locations((b, 0), (0, b), (-b, 0), (0, -b)):\n",
    "            bd.Circle(c, mode=bd.Mode.SUBTRACT)\n",
    "    bd.extrude(amount=c)\n",
    "\n",
    "show(ex6)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "68119bea",
   "metadata": {},
   "source": [
    "## 7. Polygons"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "5a47769d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "a, b, c = 60, 80, 5\n",
    "\n",
    "with bd.BuildPart() as ex7:\n",
    "    with bd.BuildSketch() as ex7_sk:\n",
    "        bd.Rectangle(a, b)\n",
    "        with bd.Locations((0, 3 * c), (0, -3 * c)):\n",
    "            bd.RegularPolygon(radius=2 * c, side_count=6, mode=bd.Mode.SUBTRACT)\n",
    "    bd.extrude(amount=c)\n",
    "\n",
    "show(ex7)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "06da7b33",
   "metadata": {},
   "source": [
    "## 8. Polylines"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "551ff3d2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "(L, H, W, t) = (100.0, 20.0, 20.0, 1.0)\n",
    "pts = [\n",
    "    (0, H / 2.0),\n",
    "    (W / 2.0, H / 2.0),\n",
    "    (W / 2.0, (H / 2.0 - t)),\n",
    "    (t / 2.0, (H / 2.0 - t)),\n",
    "    (t / 2.0, (t - H / 2.0)),\n",
    "    (W / 2.0, (t - H / 2.0)),\n",
    "    (W / 2.0, H / -2.0),\n",
    "    (0, H / -2.0),\n",
    "]\n",
    "\n",
    "with bd.BuildPart() as ex8:\n",
    "    with bd.BuildSketch(bd.Plane.YZ) as ex8_sk:\n",
    "        with bd.BuildLine() as ex8_ln:\n",
    "            bd.Polyline(pts)\n",
    "            bd.mirror(ex8_ln.line, about=bd.Plane.YZ)\n",
    "        bd.make_face()\n",
    "    bd.extrude(amount=L)\n",
    "\n",
    "show(ex8)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e86acf7d",
   "metadata": {},
   "source": [
    "## 9. Selectors, Fillets and Chamfers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "6d79b16c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "length, width, thickness = 80.0, 60.0, 10.0\n",
    "\n",
    "with bd.BuildPart() as ex9:\n",
    "    bd.Box(length, width, thickness)\n",
    "    bd.chamfer(ex9.edges().group_by(bd.Axis.Z)[-1], length=4)\n",
    "    bd.fillet(ex9.edges().filter_by(bd.Axis.Z), radius=5)\n",
    "\n",
    "show(ex9)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4d867cd1",
   "metadata": {},
   "source": [
    "## 10. Select Last and Hole"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "6786ced3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "length, width, thickness = 80.0, 60.0, 10.0\n",
    "\n",
    "with bd.BuildPart() as ex10:\n",
    "    bd.Box(length, width, thickness)\n",
    "    bd.Hole(radius=width / 4)\n",
    "    bd.fillet(ex10.edges(bd.Select.LAST).group_by(bd.Axis.Z)[-1], radius=2)\n",
    "\n",
    "show(ex10)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6d10da39",
   "metadata": {},
   "source": [
    "## 11. Use Face as Plane for BuildSketch and introduce GridLocations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "0bdd9263",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "length, width, thickness = 80.0, 60.0, 10.0\n",
    "\n",
    "with bd.BuildPart() as ex11:\n",
    "    bd.Box(length, width, thickness)\n",
    "    bd.chamfer(ex11.edges().group_by(bd.Axis.Z)[-1], length=4)\n",
    "    bd.fillet(ex11.edges().filter_by(bd.Axis.Z), radius=5)\n",
    "    bd.Hole(radius=width / 4)\n",
    "    bd.fillet(ex11.edges(bd.Select.LAST).sort_by(bd.Axis.Z)[-1], radius=2)\n",
    "    with bd.BuildSketch(ex11.faces().sort_by(bd.Axis.Z)[-1]) as ex11_sk:\n",
    "        with bd.GridLocations(length / 2, width / 2, 2, 2):\n",
    "            bd.RegularPolygon(radius=5, side_count=5)\n",
    "    bd.extrude(amount=-thickness, mode=bd.Mode.SUBTRACT)\n",
    "\n",
    "show(ex11)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fe4b4a70",
   "metadata": {},
   "source": [
    "## 12. Define Edge with a Spline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "86c4a065",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "pts = [\n",
    "    (55, 30),\n",
    "    (50, 35),\n",
    "    (40, 30),\n",
    "    (30, 20),\n",
    "    (20, 25),\n",
    "    (10, 20),\n",
    "    (0, 20),\n",
    "]\n",
    "\n",
    "with bd.BuildPart() as ex12:\n",
    "    with bd.BuildSketch() as ex12_sk:\n",
    "        with bd.BuildLine() as ex12_ln:\n",
    "            l1 = bd.Spline(pts)\n",
    "            l2 = bd.Line((55, 30), (60, 0))\n",
    "            l3 = bd.Line((60, 0), (0, 0))\n",
    "            l4 = bd.Line((0, 0), (0, 20))\n",
    "        bd.make_face()\n",
    "    bd.extrude(amount=10)\n",
    "\n",
    "show(ex12)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8a91f8ac",
   "metadata": {},
   "source": [
    "## 13. CounterBoreHoles, CounterSinkHoles and PolarLocations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "d1a43bdf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "a, b = 40, 4\n",
    "\n",
    "with bd.BuildPart() as ex13:\n",
    "    bd.Cylinder(radius=50, height=10)\n",
    "    with bd.Locations(ex13.faces().sort_by(bd.Axis.Z)[-1]):\n",
    "        with bd.PolarLocations(radius=a, count=4):\n",
    "            bd.CounterSinkHole(radius=b, counter_sink_radius=2 * b)\n",
    "        with bd.PolarLocations(radius=a, count=4,\n",
    "                               start_angle=45, angular_range=360):\n",
    "            bd.CounterBoreHole(radius=b,\n",
    "                               counter_bore_radius=2 * b,\n",
    "                               counter_bore_depth=b)\n",
    "\n",
    "show(ex13)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ca418603",
   "metadata": {},
   "source": [
    "## 14. Position on a Line with '@', '%' and introduce Sweep"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "3d6ee256",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "a, b = 40, 20\n",
    "\n",
    "with bd.BuildPart() as ex14:\n",
    "    with bd.BuildLine() as ex14_ln:\n",
    "        l1 = bd.JernArc(start=(0, 0), tangent=(0, 1), radius=a, arc_size=180)\n",
    "        l2 = bd.JernArc(start=l1 @ 1, tangent=l1 % 1, radius=a, arc_size=-90)\n",
    "        l3 = bd.Line(l2 @ 1, l2 @ 1 + (-a, a))\n",
    "    with bd.BuildSketch(bd.Plane.XZ) as ext14_sk:\n",
    "        bd.Rectangle(b, b)\n",
    "    bd.sweep()\n",
    "\n",
    "show(ex14)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9fdfd755",
   "metadata": {},
   "source": [
    "## 15. Mirroring Symmetric Geometry"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "67935819",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "a, b, c = 80, 40, 20\n",
    "\n",
    "with bd.BuildPart() as ex15:\n",
    "    with bd.BuildSketch() as ex15_sk:\n",
    "        with bd.BuildLine() as ex15_ln:\n",
    "            l1 = bd.Line((0, 0), (a, 0))\n",
    "            l2 = bd.Line(l1 @ 1, l1 @ 1 + (0, b))\n",
    "            l3 = bd.Line(l2 @ 1, l2 @ 1 + (-c, 0))\n",
    "            l4 = bd.Line(l3 @ 1, l3 @ 1 + (0, -c))\n",
    "            l5 = bd.Line(l4 @ 1, (0, (l4 @ 1).Y))\n",
    "            bd.mirror(ex15_ln.line, about=bd.Plane.YZ)\n",
    "        bd.make_face()\n",
    "    bd.extrude(amount=c)\n",
    "\n",
    "show(ex15)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4bd21479",
   "metadata": {},
   "source": [
    "## 16. Mirroring 3D Objects"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ba510d56",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "length, width, thickness = 80.0, 60.0, 10.0\n",
    "\n",
    "with bd.BuildPart() as ex16_single:\n",
    "    with bd.BuildSketch(bd.Plane.XZ) as ex16_sk:\n",
    "        bd.Rectangle(length, width)\n",
    "        bd.fillet(ex16_sk.vertices(), radius=length / 10)\n",
    "        with bd.GridLocations(x_spacing=length / 4, y_spacing=0,\n",
    "                              x_count=3, y_count=1):\n",
    "            bd.Circle(length / 12, mode=bd.Mode.SUBTRACT)\n",
    "        bd.Rectangle(length, width,\n",
    "                     align=(bd.Align.MIN, bd.Align.MIN),\n",
    "                     mode=bd.Mode.SUBTRACT)\n",
    "    bd.extrude(amount=length)\n",
    "\n",
    "with bd.BuildPart() as ex16:\n",
    "    bd.add(ex16_single.part)\n",
    "    bd.mirror(ex16_single.part, about=bd.Plane.XY.offset(width))\n",
    "    bd.mirror(ex16_single.part, about=bd.Plane.YX.offset(width))\n",
    "    bd.mirror(ex16_single.part, about=bd.Plane.YZ.offset(width))\n",
    "    bd.mirror(ex16_single.part, about=bd.Plane.YZ.offset(-width))\n",
    "\n",
    "show(ex16)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8568f086",
   "metadata": {},
   "source": [
    "## 17. Mirroring from Faces"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "f5d8da14",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c\n"
     ]
    }
   ],
   "source": [
    "a, b = 30, 20\n",
    "\n",
    "with bd.BuildPart() as ex17:\n",
    "    with bd.BuildSketch() as ex17_sk:\n",
    "        bd.RegularPolygon(radius=a, side_count=5)\n",
    "    bd.extrude(amount=b)\n",
    "    bd.mirror(ex17.part, about=bd.Plane(ex17.faces().group_by(bd.Axis.Y)[0][0]))\n",
    "\n",
    "show(ex17)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "671dbf3a",
   "metadata": {},
   "source": [
    "## 18. Creating Workplanes on Faces"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "1478c3df",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "c\n"
     ]
    }
   ],
   "source": [
    "length, width, thickness = 80.0, 60.0, 10.0\n",
    "a, b = 4, 5\n",
    "\n",
    "with bd.BuildPart() as ex18:\n",
    "    bd.Box(length, width, thickness)\n",
    "    bd.chamfer(ex18.edges().group_by(bd.Axis.Z)[-1], length=a)\n",
    "    bd.fillet(ex18.edges().filter_by(bd.Axis.Z), radius=b)\n",
    "    with bd.BuildSketch(ex18.faces().sort_by(bd.Axis.Z)[-1]):\n",
    "        bd.Rectangle(2 * b, 2 * b)\n",
    "    bd.extrude(amount=-thickness, mode=bd.Mode.SUBTRACT)\n",
    "\n",
    "show(ex18)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7391ee4f",
   "metadata": {},
   "source": [
    "## 19. Locating a Workplane on a Vertex"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a7c286c9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+\n"
     ]
    }
   ],
   "source": [
    "length, thickness = 80.0, 10.0\n",
    "\n",
    "with bd.BuildPart() as ex19:\n",
    "    with bd.BuildSketch() as ex19_sk:\n",
    "        bd.RegularPolygon(radius=length / 2, side_count=7)\n",
    "    bd.extrude(amount=thickness)\n",
    "    topf = ex19.faces().sort_by(bd.Axis.Z)[-1]\n",
    "    vtx = topf.vertices().group_by(bd.Axis.X)[-1][0]\n",
    "    vtx2Axis = bd.Axis((0, 0, 0), (-1, -0.5, 0))\n",
    "    vtx2 = topf.vertices().sort_by(vtx2Axis)[-1]\n",
    "    with bd.BuildSketch(topf) as ex19_sk2:\n",
    "        with bd.Locations((vtx.X, vtx.Y), (vtx2.X, vtx2.Y)):\n",
    "            bd.Circle(radius=length / 8)\n",
    "    bd.extrude(amount=-thickness, mode=bd.Mode.SUBTRACT)\n",
    "\n",
    "show(ex19)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9d38d9e4",
   "metadata": {},
   "source": [
    "## 20. Offset Sketch Workplane"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6304975e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "11bd76eb",
   "metadata": {},
   "source": [
    "## 21. Create a Workplane in the center of another Shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d437887",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
